package com.thepitch.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Container for a team's aggregated home or away statistics.
 * Fields are populated by TeamProfileAnalyzer:
 *   - Goals / cleanSheets / bttsCount → from match results (always real)
 *   - Shots / xG / cards / corners    → from match_stats table (FBref CSV import)
 *   - dataSource                       → tells you which source was used
 */
public class TeamProfile {

    // ── Identity ──────────────────────────────────────────────────────────────
    public String  teamName;
    public boolean isHome;

    /** Where the advanced stats came from — "FBref (19 matches)" or "League Average Fallback" */
    public String dataSource = "Not loaded";

    // ── Goal stats (from match results — always real data) ────────────────────
    public double goalsScored;
    public double goalsConceded;
    public int    cleanSheets;
    public int    bttsCount;

    // ── Shot stats (from match_stats table / FBref) ────────────────────────────
    public double shotsTotal;
    public double shotsOnTarget;
    public double shotAccuracy;   // percentage

    // ── Expected Goals (from match_stats table / FBref) ───────────────────────
    public double xG;             // xG produced per game
    public double xGConceded;     // xG conceded per game (opponent's xG)

    // ── Set piece / discipline (from match_stats table / FBref) ──────────────
    public double cornersFor;
    public double cornersAgainst;
    public double yellowCards;
    public double redCards;
    public double fouls;

    // ── Possession (optional — FBref doesn't expose this per match easily) ───
    public double possession;

    // ── Streak alerts (generated by TeamProfileAnalyzer) ─────────────────────
    public List<String> streakAlerts = new ArrayList<>();

    // ── toString for console display ──────────────────────────────────────────
    @Override
    public String toString() {
        return String.format(
            "   Goals:   %.2f scored/game  |  %.2f conceded/game%n" +
            "   Shots:   %.1f/game  |  On target: %.1f  (%.0f%%)%n" +
            "   xG:      %.2f/game%n" +
            "   Corners: %.1f/game%n" +
            "   Cards:   %.1f yellow  |  %.1f red  |  %.1f fouls%n" +
            "   Streaks: CS=%d  BTTS=%d%n" +
            "   Source:  %s",
            goalsScored, goalsConceded,
            shotsTotal, shotsOnTarget, shotAccuracy,
            xG,
            cornersFor,
            yellowCards, redCards, fouls,
            cleanSheets, bttsCount,
            dataSource
        );
    }
}
